version: "3.9"
services:
  postgres:
    image: postgres:16.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: "rest-db"
      POSTGRES_USER: "postgresql"
      POSTGRES_PASSWORD: "postgresql"
    ports:
      - "5432:5432"
    volumes:
      - rest-db:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d

volumes:
 rest-db:
   external: false
